### PR TITLE
Fix Initialize/Terminate race condition

### PR DESCRIPTION
**Pull request by HeyImAlex**
At least, I think this is a potential race condition...

### CODE REVIEW

**Comment by phacops** [comment]
I think each of this functions are supposed to be called only once in the lifetime of a program anyway. Instead of a `Mutex`, I would called a `Once` (http://golang.org/pkg/sync/#Once) to make sure it's really the case.

**Comment by HeyImAlex** [comment]
@phacops I considered it, but it would take some changes to Terminate, and it could potentially break user code. This is a simple solution that absolutely doesn't break anything and just works. The only thing I can see Once improving is perf, but this isn't exactly a hot code path :smile:

**Comment by phacops** [comment]
To be honest, I don't see how this will help. Now, we have a mutex and a `initialized` boolean value to make sure we execute only once some functions (which are supposed to be called once anyway).

The way I see it, either leave it the way it is or "improve" it using a `Once` for both function. And even for the latter, I'm not sure we'll gain something.

**Comment by HeyImAlex** [comment]
It's a race condition; MagickWandGenesis can be called twice because there's not a mutex protecting initialized. Image you start a bunch of goroutines...

```golang
for i := 0; i < 10; i++ {
    go func() {
        magick.Initialize()
        // process some images
    }
}
```

If GOMAXPROCS > 0 (which it will be by default in 1.5) you can't count on that code being safe. At least... I think

```text
goroutine 1           | goroutine 2
-------------------------------------------
if initialized {      | .
    return            | .
}                     | .
.                     | if initialized {
.                     |     return
.                     | }
C.MagickWandGenesis() | .
initialized = true    | .
.                     | C.MagickWandGenesis()
.                     | initialized = true
```

**Comment by phacops** [comment]
But that's the thing, this function is documented as being needed to be called once. So, if you're doing this, you're already doing it wrong (http://www.imagemagick.org/discourse-server/viewtopic.php?t=8740). I totally get why it would be a race condition if it's called multiple times, but the function in itself is not designed to be called several times. So why bother?

So, we can improve the documentation to make it clear that you only need to call it once before everything else, or I would suggest using `Once` if you really want to change this piece of code.

**Comment by HeyImAlex** [comment]
Come to think of it, this code is pretty much impossible to protect against...

```golang
for i := 0; i < 10; i++ {
    go func() {
        magick.Initialize()
        defer magick.Terminate()
        // do some work
    }
}
```

There's definitely an argument to be made to remove the `initialized` checks all together and let the user shoot themselves in the foot.

If the goal is to handle it on the go side, maybe we should panic when trying to initialize twice? Then at least the user will know their code is bad fast instead of running into an obscure race condition down the line.

My only problem with Once is it takes something away from the api. Are you sure there's _absolutely no_ valid use case for creating and destroying IM through the lifecycle of an application? Should that be a decision this lib makes?

Anyways, a whole lot of bikeshedding :smile:

**Comment by phacops** [comment]
I'm not sure why anybody would create and destroy IM through the lifecycle of an application. I can't say there is absolutely no use case. What I can say is this function was created by the ImageMagick devs as something to call once and only once. As a lib making a one-to-one interface with the C code, we should keep this behaviour I think.

But I do see why you'd want to protect against that and so potentially allowing people to init/free several times. I just think we should stick to mimicking the C bindings.

**Comment by justinfx** [comment]
I also hadn't really though of trying to protect these functions, since in
my own application I also only Initialize once for the whole app (not in a
number of goroutines).

**Comment by justinfx** [comment]
Another pull request (#62) which wants to introduce finalizers to object destruction, also chucked in a `sync.Once` change to the Initialize/Terminate process that was discussed in this issue. Does anyone from this thread have an opinion, or object to it being merged in (just the sync part in particular)?

**Comment by phacops** [comment]
I have nothing new to add. I don't think it's needed but it doesn't hurt.

**Comment by JekaMas** [comment]
As i can see it is a potencially memory leak in precent code:
We call Initialize() first time, it call C.MagickWandGenesis(), if after it Terminate() called it will not make anything because initialized is not set to true. Terminate() does not return an error, but it will not no anything and all resources C.MagickWandGenesis() are leak.
It`ll be nice to guarantee for user that package always free all resources.

**Comment by phacops** [comment]
Still, this case won't happen if the developer reads the docs. It explicitly says to call the `Initialize` and `Terminate` only once and in the same routine. So yes, it'd be helpful if you call that in different goroutinrs but that's wrong in the first place.

I don't mind extra protection, and since we're automating all the release of memory it might be safer to put this in the PR because less and less people will pay attention to that detail (memory management). So go for it.

**Comment by justinfx** [comment]
I'm closing this because the init and term functionality was merged. Anything beyond that just seems like misuse

**Pull request closed without merging**
