### PR TITLE
Now compiles on 32 bit machines. Added file with compiler flag.

### PR DESCRIPTION
**Pull request by joonazan**

### CODE REVIEW

**Comment by phacops** [comment]
Maybe you could add a `// +build 386` to only build with 32 bits arch.

**Comment by joonazan** [comment]
Sounds like a good idea. Should I close and make a new pull request?

**Comment by phacops** [comment]
No, just add a new commit or amend this one.

**Comment by joonazan** [comment]
Ok, did that.

**Comment by justinfx** [comment]
Thanks for this.

**Pull request merged**
