### PR TITLE
Free this string as it's not a const char *

### PR DESCRIPTION
**Pull request by phacops**

### CODE REVIEW

**Comment by phacops** [comment]
BTW, master is broken without this.

**Comment by phacops** [comment]
@justinfx sorry for the trouble.

**Comment by justinfx** [comment]
Done :-)

**Comment by phacops** [comment]
Thank you.

**Comment by justinfx** [comment]
And thanks for the quick contributions. I wouldn't have gotten a chance to
look at it until tomorrow.

**Pull request merged**
