### PR TITLE
fixed to memory leak, QueryFonts, QueryFormats, GetImageArtifacts, GetImageProfiles, GetImageProperties, GetOptions

### PR DESCRIPTION
**Pull request by yoya**
* free to strings array on sizedCStringArrayToStringSlice.
* callers to sizedCStringArrayToStringSlice
  - QueryConfigureOptions : free excute <= dismiss!
  - QueryFonts        : no free
  - QueryFormats      : no free
  - GetImageArtifacts : no free
  - GetImageProfiles  : no free
  - GetImageProperties: no free
  - GetOptions        : no free

### CODE REVIEW

**Comment by justinfx** [comment]
Freeing the pointer inside of `sizedCStringArrayToStringSlice`, when it doesn't own it, feels wrong. Do you think it might be better to free them at the call sites where the memory was allocated?

**Comment by yoya** [comment]
From the point of view, locality and unity of strings as object.
I think clear that free to the array of string & each strings in the same function.

**Comment by justinfx** [comment]
I think we have some more work to be done, surrounding this issue. There are inconsistencies between `sizedCStringArrayToStringSlice`, the other utility conversion functions in that file, and the usages:

https://github.com/gographics/imagick/search?utf8=%E2%9C%93&q=sizedDoubleArrayToFloat64Slice&type=Code

There is a mixture of no freeing, and freeing only part of the memory. I might try and expand your work to cover this, but I won't get to it most likely until the weekend. If you are feeling adventurous and want to do it before me, I will merge it! :-)

**Comment by yoya** [comment]
I agree all. I'm making pull request base on alternate idea. plz wait.

**Comment by yoya** [comment]
new PR is here > https://github.com/gographics/imagick/pull/37

**Pull request closed without merging**
