### PR TITLE
Add examples/docker (refs #173)

### PR DESCRIPTION
**Pull request by justinfx**
Adds a docker example for imagick.v3

### CODE REVIEW

**Comment by hugoglt** [comment]
seems like not work : 

```
W: The repository 'http://security.debian.org/debian-security stretch/updatesRelease' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' doesnot have a Release file.
E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device)
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: Nospace left on device)
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write(28: No space left on device)
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

`docker build -t imagicktest .` in `gographics/imagick/examples/docker`

**Comment by justinfx** [comment]
@hugoglt are you sure you have a working docker install? It can't even seem to pull the required image layers to start building your docker image. You may want to check your docker install instructions for your particular operating system.

**Comment by hugoglt** [comment]
normally my docker install is good, i work with docker every day, i will try with another environnement to be sure

**Comment by hugoglt** [comment]
yes you right, it work with an other environnement, sorry for this

**Pull request merged**
