### PR TITLE
Make mw, pi, pw, dw objects destroyable in GO GC

### PR DESCRIPTION
**Pull request by JekaMas**
I suppose imagick should support GO GC. So i create new interface for structs with Destroy() method and add this call in GC stage.

### CODE REVIEW

**Comment by justinfx** [comment]
First off, thanks for doing this work!

Since this is a change to the way objects are managed, and impacts existing code that has been manually destroying, can we add a test that ensures that calling Destroy() multiple times will always be safe? I realize that the Destroy() logic checks if the private pointer is nil and does nothing if it has been destroyed already, we probably want to make sure we don't break existing code in the future by this ever accidentally changing (since we are introducing a second Destroy() call for code that already did it manually).

Maybe instead of having a ton of SetFinalizer calls introduced all over the source code, we could just make a private `newMagickWand(*C.MagickWand) *MagickWand` function that will create the new instance and set the finalizer all in one place. That would make all the other construction sites a bit cleaner IMHO.

I see you snuck in changes to Initialize/Terminate [here](https://github.com/gographics/imagick/pull/62/files#diff-77783251162db23891444f5962e383dfL17). This was something that was discussed in pull request #43 , so maybe we should just get some final opinions from those that previously had input?

**Comment by pkieltyka** [comment]
this is awesome!

**Comment by JekaMas** [comment]
Nice ideas! Thank you so much!
I make some refactoring in code and tests.
According benchmarks this commits haven`t influence on package speed (we use this code on Highload - 50-200 images for resize and format conversation in sec).

**Comment by justinfx** [comment]
I'm a little concerned about the new complexity that has been added, with the reference counting, channel sync, and shutdown checking. Is there any possibility we could deadlock on the call to terminate, based on the docs for `SetFinalizer?`

https://golang.org/pkg/runtime/#SetFinalizer
> There is no guarantee that finalizers will run before a program exits

I'm probably completely wrong here, since once you block on Terminate, the finalizers will eventually run (I think). It just feels a bit scary to synchronize around the behaviour of finalizers.

**Comment by justinfx** [comment]
@JekaMas , if you split out the fixes to Initialize/Terminate into its own pull request, I can merge that and close the related #43 . I'm still interested in hearing if you or anyone else has an opinion on the concerns about relying on syncing with finalizers during terminate. As long as one other person feels it isn't a problem, then we could merge it.

**Comment by justinfx** [comment]
Relevant discussion happening now on golang-nuts, about finalizers: https://groups.google.com/d/topic/golang-nuts/Hd0uPrKIDww/discussion

An interesting point that Ian makes is that if the Go GC were to be cleaning up very slowly because there isn't much Go garbage, but you had a bunch of C memory being allocated quickly, you may get slow freeing of your C memory that is being managed by finalizers. I hope that isn't a negative impact here. Users should still be able to call Destroy() to explicitly free memory when they want, and the finalizers running would end up being a no-op.

**Comment by pkieltyka** [comment]
It would be great to merge this. We've been using the fork in production and everything has been operating as normal, if not better for parts we've potentially missed.

**Comment by phacops** [comment]
Any performance différence?

**Comment by pkieltyka** [comment]
@phacops no performance issues that we could see. instruments remained consistent.

**Comment by justinfx** [comment]
So, no one has concerns about the synchronization around finalizers, in the call to terminate?

**Comment by justinfx** [comment]
I still feel the `sync.Once` should be a private member of the structs and not embedded to be publicly accessible.

**Comment by phacops** [comment]
Looks good to me. I don't think the public `sync.Once` is such a big deal but it wouldn't hurt.

**Comment by justinfx** [comment]
@phacops , its not just the public `sync.Once` that has been added to the public API, but also the `Increment / Decrement` calls. I don't see why it is a good idea to expose those public methods. It seems it could really hurt things is someone started calling them for whatever reason. It could break the reference counting and cause lockups, right?

**Comment by phacops** [comment]
Hum true, we don't need that to be public.

**Comment by justinfx** [comment]
A user has encountered a memory leak in their code from a subtle bug of not destroying a wand that was returned from another function (#72). It makes me think that we should try and move forward on merging this. Do you think we could fix up that last suggestion of not embedding a public `sync.Once` into the structs and just composing it as an unexported field?

**Comment by xealot** [comment]
I'm a big fan of trying to tighten the memory leakiness of this package... 

I have profiled myself silly trying to fine objet accumulation and places where I may not be clearing or destroying something but I cannot.

**Comment by justinfx** [comment]
Happy to merge it if we get the `sync.Once` thing fixed. I can just do it this weekend if @JekaMas doesn't get to it.

**Comment by justinfx** [comment]
I've done the final clean ups in #80. I will merge it in 24 hours, unless anyone has any last minute input.

**Comment by rogierlommers** [comment]
No real input, except a big "thanks" for the work!

**Comment by justinfx** [comment]
Merged in #80 
Tagged as v1.1.0 / v2.2.0

**Pull request closed without merging**
